import csv

products = [
    {
        "handle": "golden-argan-rose-youth-serum",
        "title": "سيروم الأركان الذهبي والورد النقّي — Golden Argan & Rose Serum",
        "body": "<p>سيروم ملكي مركز بزيت الأركان العضوي المقشر بقطرات الورد البلدي المغربي لتجديد خلايا البشرة وإعادة النضارة الفائقة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Facial Serum",
        "tags": "Facial Skincare, Rare Oils, Best Sellers, سيروم, الأركان, الأكثر مبيعاً",
        "sku": "NAT-SKN-001",
        "price": "350.00",
        "compare_at": "450.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "pure-prickly-pear-anti-aging-elixir",
        "title": "أكسير التين الشوكي الخالص للمقاومة والتجاعيد — Prickly Pear Elixir",
        "body": "<p>الإكسير الذهبي الأكثر ندرة في العالم. زيت بذور التين الشوكي المغربي المعصور على البارد 100% لتنعيم الخطوط الدقيقة وشد البشرة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Rare Oils",
        "tags": "Rare Oils, Facial Skincare, Best Sellers, التين الشوكي, زيوت نادرة",
        "sku": "NAT-SKN-002",
        "price": "490.00",
        "compare_at": "620.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1608248597266-c0c4515a4437?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "pure-rose-chamomile-clarifying-toner",
        "title": "تونر مقشر ومُنعش بماء الورد والبابونج — Clarifying Rose Water Toner",
        "body": "<p>رذاذ منعش يوازن حموضة البشرة، يقلل من حجم المسام ويعزز امتصاص السيرومات بتركيبة ماء الورد المقطر عالي النقاء.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Toner",
        "tags": "Facial Skincare, Best Sellers, تونر, ماء الورد",
        "sku": "NAT-SKN-003",
        "price": "190.00",
        "compare_at": "240.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "orange-blossom-niacinamide-radiance-cream",
        "title": "كريم النياسيناميد وزهر البرتقال للإشراقة — Orange Blossom Cream",
        "body": "<p>مرطب ذو قوام حريري خفيف يدمج بين قوة النياسيناميد المقوية للحاجز الجلدي وعطر زهر البرتقال المغربي لتوحيد لون البشرة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Face Cream",
        "tags": "Facial Skincare, Best Sellers, كريم, زهر البرتقال",
        "sku": "NAT-SKN-004",
        "price": "320.00",
        "compare_at": "400.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "chamomile-oat-gentle-hydrating-cleanser",
        "title": "منظف الوجه بالبابونج الشافي والشوفان — Gentle Hydrating Cleanser",
        "body": "<p>منظف رغوي لطيف خالٍ من الكبريتات يزيل الشوائب والمكياج دون تجفيف البشرة، مخصص للبشرة الحساسة والجافة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Cleanser",
        "tags": "Facial Skincare, منظف البشرة, بابونج",
        "sku": "NAT-SKN-005",
        "price": "210.00",
        "compare_at": "270.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1556228722-d1191d098e9b?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "atlas-clay-activated-charcoal-detox-mask",
        "title": "قناع الطين الأطلسي والفحم المنشط — Atlas Clay Detox Mask",
        "body": "<p>قناع الطين البركاني الأطلسي الغني بالمعادن والفحم المنشط لتنقية المسام والتخلص من سموم الجلد والزيوت الزائدة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Face Mask",
        "tags": "Facial Skincare, قناع الوجه, طين أطلسي",
        "sku": "NAT-SKN-006",
        "price": "260.00",
        "compare_at": "330.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1567928256057-0a2578508e70?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "atlas-saffron-multi-hyaluronic-dew-serum",
        "title": "سيروم الهيالورونيك مع الزعفران الحر — Atlas Saffron Dew Serum",
        "body": "<p>سيروم ترطيب عميق بـ 4 أوزان جزيئية للهيالورونيك مستخلص مع مضادات الأكسدة النادرة لزعفران تاليوين الأصيل.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Facial Serum",
        "tags": "Facial Skincare, Best Sellers, زعفران, هيالورونيك",
        "sku": "NAT-SKN-007",
        "price": "380.00",
        "compare_at": "480.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "eucalyptus-mint-botanical-body-oil",
        "title": "زيت الجسم الملكي باليوكاليبتوس والنعناع — Botanical Body Oil",
        "body": "<p>زيت جسم غني وسريع الامتصاص يجمع بين خواص الاسترخاء المنعشة لليوكتليبتوس والنعناع المغربي لتنعيم البشرة المرهقة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Body Oil",
        "tags": "Body Care, زيت الجسم, يوكاليبتوس",
        "sku": "NAT-BDY-008",
        "price": "280.00",
        "compare_at": "350.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1608248597266-c0c4515a4437?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "royal-black-soap-scrub-herbal-infusion",
        "title": "مقشر الصابون البلدي الملكي بالأعشاب — Royal Moroccan Black Soap",
        "body": "<p>مقشر الصابون الأسود التقليدي المعزز بعصارة الزيتون والأعشاب الجبلية لتنظيف وتنعيم الجسم على طريقة الحمام المغربي الملكي.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Body Scrub",
        "tags": "Body Care, Best Sellers, صابون بلدي, حمام مغربي",
        "sku": "NAT-BDY-009",
        "price": "180.00",
        "compare_at": "230.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "rich-shea-argan-velvet-body-butter",
        "title": "زبدة الشيا والأركان لترطيب الجسم العميق — Velvet Body Butter",
        "body": "<p>زبدة مخملية فاخرة تغذي البشرة شديدة الجفاف وتعيد إليها مرونتها بتركيبتها المغذية من الشيا الخام وزيت الأركان.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Body Butter",
        "tags": "Body Care, زبدة الجسم, الشيا, الأركان",
        "sku": "NAT-BDY-010",
        "price": "290.00",
        "compare_at": "370.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1567928256057-0a2578508e70?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "pure-rose-honey-lip-nourishing-balm",
        "title": "بلسم الشفاه المغذي بالورد وشمع العسل — Pure Rose Lip Balm",
        "body": "<p>مرطب شفاه طبيعي يدوم طويلاً يجمع بين خلاصة الورد البلدي وشمع العسل العضوي لحماية الشفاه من الجفاف والتشققات.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Lip Care",
        "tags": "Facial Skincare, Body Care, بلسم الشفاه, ورد",
        "sku": "NAT-LIP-011",
        "price": "95.00",
        "compare_at": "130.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "nutritive-argan-sweet-almond-hair-mask",
        "title": "ماسك قناع الشعر باللوز وزيت الأركان — Nutritive Hair Mask",
        "body": "<p>علاج ترطيب مكثف للشعر التالف والمجهد يعيد اللمعان والقوة لخصلات الشعر من الجذور حتى الأطراف.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Hair Care",
        "tags": "Body Care, ماسك الشعر, أركان",
        "sku": "NAT-HAR-012",
        "price": "270.00",
        "compare_at": "340.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "cooling-cucumber-peppermint-eye-serum",
        "title": "سيروم محيط العين بالقطر والنعناع البري — Cooling Eye Serum",
        "body": "<p>سيروم بكرة دوارة من الفولاذ البارد لتهدئة انتفاخات محيط العين وتفتيح الهالات السوداء بخلاصة الخيار والنعناع.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Eye Care",
        "tags": "Facial Skincare, سيروم العين, هالات سوداء",
        "sku": "NAT-EYE-013",
        "price": "310.00",
        "compare_at": "390.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "pure-sweet-almond-botanical-oil",
        "title": "زيت اللوز الحلو المغذي للبشرة الحساسة — Sweet Almond Oil",
        "body": "<p>زيت معصور على البارد نقي 100% مناسب لجميع أنواع البشرة والبشرة الحساسة للترطيب والتدليك اليومي.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Rare Oils",
        "tags": "Rare Oils, زيت اللوز, زيوت نادرة",
        "sku": "NAT-OIL-014",
        "price": "220.00",
        "compare_at": "280.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1608248597266-c0c4515a4437?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "royal-moroccan-hammam-ritual-set",
        "title": "مجموعة طقوس الحمام الملكي — Royal Moroccan Hammam Set",
        "body": "<p>مجموعة فاخرة تتضمن الصابون البلدي الملكي، قناع الغاسول المخصب، ليفة كيس ممتازة وزيت الجسم المنعش.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Gift Set",
        "tags": "Gift Sets, Best Sellers, طقوس الحمام, مجموعات هدايا",
        "sku": "NAT-SET-015",
        "price": "650.00",
        "compare_at": "850.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "radiance-youth-botanical-facial-set",
        "title": "مجموعة التوهج والنضارة للوجه — Radiance Botanical Set",
        "body": "<p>ثنائية تجديد الشباب الفاخرة: سيروم الأركان والورد + أكسير التين الشوكي النادر لترطيب ونضارة لا مثيل لها.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Gift Set",
        "tags": "Gift Sets, Best Sellers, مجموعة النضارة, هدايا فاخرة",
        "sku": "NAT-SET-016",
        "price": "790.00",
        "compare_at": "990.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "calming-lavender-rosemary-massage-oil",
        "title": "زيت اللافندر والنعناع للاسترخاء والتدليك — Lavender Massage Oil",
        "body": "<p>مزيج مهدئ من الزيوت النباتية العطرية المخصصة للمساعدة على الاسترخاء العميق وتخفيف التوتر العضلي.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Body Oil",
        "tags": "Body Care, Rare Oils, زيت المساج, لافندر",
        "sku": "NAT-OIL-017",
        "price": "240.00",
        "compare_at": "310.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1608248597266-c0c4515a4437?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "hand-velvet-cream-argan-rose",
        "title": "كريم اليدين بالورد والأركان المغذي — Hand Velvet Cream",
        "body": "<p>كريم يدين خفيف وغني بالمغذيات يمتص بسرعة ليترك اليدين بنعومة حريرية ورائحة ورد جوري ساحرة.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Hand Care",
        "tags": "Body Care, كريم اليدين, الورد",
        "sku": "NAT-HND-018",
        "price": "140.00",
        "compare_at": "180.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "gentle-jojoba-exfoliating-facial-polish",
        "title": "مقشر الوجه بلطف بحبيبات الجوجوبا — Jojoba Facial Polish",
        "body": "<p>مقشر دقيق بحبيبات الجوجوبا الكروية الدقيقة لإزالة الخلايا الميتة بلطف وتنعيم البشرة دون التسبب في أي تهيج.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Facial Scrub",
        "tags": "Facial Skincare, مقشر الوجه, جوجوبا",
        "sku": "NAT-SKN-019",
        "price": "230.00",
        "compare_at": "290.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=800&auto=format&fit=crop"
    },
    {
        "handle": "sleep-well-aromatherapy-pillow-mist",
        "title": "بخاخ الزيوت العطرية للنوم والوسادة — Sleep Well Pillow Mist",
        "body": "<p>بخاخ عطري طبيعي مستخلص من اللافندر والبابونج لتهيئة الأجواء لنوم عميق ومريح.</p>",
        "vendor": "Natura Luxe Skincare",
        "type": "Aromatherapy",
        "tags": "Body Care, بخاخ الوسادة, لافندر",
        "sku": "NAT-MST-020",
        "price": "160.00",
        "compare_at": "210.00",
        "qty": "100",
        "image": "https://images.unsplash.com/photo-1617897903246-719242758050?q=80&w=800&auto=format&fit=crop"
    }
]

headers = [
    "Handle", "Title", "Body (HTML)", "Vendor", "Standardized Product Type", 
    "Custom Product Type", "Tags", "Published", "Option1 Name", "Option1 Value", 
    "Option2 Name", "Option2 Value", "Option3 Name", "Option3 Value", 
    "Variant SKU", "Variant Grams", "Variant Inventory Tracker", "Variant Inventory Qty", 
    "Variant Inventory Policy", "Variant Fulfillment Service", "Variant Price", 
    "Variant Compare At Price", "Variant Requires Shipping", "Variant Taxable", 
    "Variant Barcode", "Image Src", "Image Position", "Image Alt Text", 
    "Gift Card", "SEO Title", "SEO Description", "Google Shopping / Condition", "Status"
]

with open('sample_products_import.csv', mode='w', newline='', encoding='utf-8-sig') as f_out:
    writer = csv.writer(f_out)
    writer.writerow(headers)
    for p in products:
        writer.writerow([
            p['handle'],
            p['title'],
            p['body'],
            p['vendor'],
            'Beauty > Skin Care',
            p['type'],
            p['tags'],
            'TRUE',
            'Title',
            'Default Title',
            '', '', '', '',
            p['sku'],
            '250',
            'shopify',
            p['qty'],
            'deny',
            'manual',
            p['price'],
            p['compare_at'],
            'TRUE',
            'FALSE',
            '',
            p['image'],
            '1',
            p['title'],
            'FALSE',
            p['title'],
            p['title'],
            'new',
            'active'
        ])

print("Successfully generated sample_products_import.csv with 20 items and quantity 100.")

